### ISSUE TITLE
Add translations of the "choose_range" text

### ISSUE THREAD

**Issue by stevecotton** [TeamSurvivalXtreme/SXCollection#10]
Translating the whole of SXC is out of scope of this, but I think the question that unlocks the shop should be translated in to players' languages, ideally we'll find an already-translated string in mainline Wesnoth which can be used for half of this.

> Before you will be able to buy damage and strikes training,
> you must choose which range training you will focus on.
> Other range will become much harder to improve and it will
> cause that it will cost double price of the selected range.

We should also correct the grammar in the English text.

**Comment by stevecotton** [comment]
I've looked for an already-translated string, and didn't find a reusable one (looked in core, manual, AToTB, HTTT and TSG). SXCR takes the alternative approach of forcing the player to choose before the shop dialog opens, but that inhibits the possibility of having a spare character for a player who joins later, but that needs hp and movement points while waiting.

**Comment by Jordy-Jordan** [comment]
I can translate the whole shopping features in french and spanish, once I know what and where to change.
But we could start with keytexts

**Comment by Jordy-Jordan** [comment]
After some searchs, I found the safest way to do it is to add sxc maps and wished strings in every file.po from https://github.com/wesnoth/wesnoth/tree/master/po/wesnoth-multiplayer, and wait for every language team to approve and pull it on the next bfw release. In other words, lets be risky and scratch sthg...

**Comment by stevecotton** [comment]
While there's much more to translate, the "choose range" text itself was done in 2b681e2fbcfbb7ebd1a117f859bde5d579dc4ccf.
