### ISSUE TITLE
Shop graphics glitch on SXC-Isar's

### ISSUE THREAD

**Issue by stevecotton** [TeamSurvivalXtreme/SXCollection#16]
On Isar's, elven.png looks bad.

**Comment by Jordy-Jordan** [comment]
It looks like any elven village look bad beside hills, I found that drake5.png was perfect on Isar, we could use it unless you want to use a human village.

**Comment by stevecotton** [comment]
drake5 sounds good to me

**Comment by stevecotton** [comment]
Fixed in 89d876c2aea915f04edf28bc55220f2341378096, thanks Jordy.
