### ISSUE TITLE
Missing units in SXC eras

### ISSUE THREAD

**Issue by Jordy-Jordan** [TeamSurvivalXtreme/SXCollection#18]
Ghost,Dwarvish Scout and more... are missing from SXC era... Hopefully it's easy to solve.  But SXC team former could have added it... There should be a reason they haven't.

**Comment by stevecotton** [comment]
I think it's just that some unit types become fairly generic in the context of SXC, and so there's no reason to have all of them.

With nerfs removing both drains and nightstalk, a Ghost becomes similar to a bat or drake.

With movement available in the shop, the Dwarvish Scout becomes a fairly generic dwarf.

81f2fff36f0dadc1bdffbf73144ff60cbe92faaa adds a couple of dunefolk. I'd be open to new issues for suggestions of specific unit types, but going to close this as not adding the two named ones.
