### ISSUE TITLE
Revive is documented, but doesn't work

### ISSUE THREAD

**Issue by stevecotton** [TeamSurvivalXtreme/SXCollection#26]
In 3e7b62b934dacaaa343eea4d44e6225403f09c92, rookie mode documents that it will support reviving characters; but it fails with "warning engine: variable_info: invalid WML array index, dead[0]".

Before 0.2.119 we should either fix it or remove the documentation.

**Comment by Jordy-Jordan** [comment]
yh an unclosed loop is guilty
