### ISSUE TITLE
SXC Mythos - some Therian units have been removed from AE

### ISSUE THREAD

**Issue by stevecotton** [TeamSurvivalXtreme/SXCollection#57]
AE 4.16 removed the `AE_myh_therians_Therian_Wildcat`, and possibly others used in SXC Mythos.

**Comment by stevecotton** [comment]
Or possibly just renamed, it seems to be AE_myh_Wildcat now.
The Leopard is now AE_myh_Tiger (but it's still a Leopard in the UI).

**Comment by sevu** [comment]
The got all renamed from AE_myh_****_xyz to AE_myh_xyz, as the EoM era already guarantees that there are now units with the same Id within. This change was made to change the files from EoM to AE by a script.

**Comment by stevecotton** [comment]
Fixed in 2dda414f97f4b888d4c78832f4cbb6f06b2a4405, released in sxc_v0.2.127.
